test(
  function failing () { throw new Error() },
  returns()
)
